syslog-ng: added support of running process as non-privileged user (#58)
* syslog-ng: added support of running process as non-privileged user.

* syslog-ng: added checks.

* syslog-ng: added LOG_FILE option.

* syslog-ng: added %{service_user} and %{service_group}.

* syslog-ng: use 'syslog-ng' instead of 'service'.

* syslog-ng: use 'syslog-ng' user in sysconfig.

diff --git a/syslog-ng/SOURCES/syslog-ng.init b/syslog-ng/SOURCES/syslog-ng.init
--- a/syslog-ng/SOURCES/syslog-ng.init
+++ b/syslog-ng/SOURCES/syslog-ng.init
@@ -12,21 +12,24 @@ source /etc/init.d/kaosv
 ###############################################################################
 
 kv[prog_name]="syslog-ng"
+kv[pid_file]="/var/run/syslog-ng/syslog-ng.pid"
 
 kv.readSysconfig
 
 binary="${BINARY:-/usr/sbin/syslog-ng}"
 conf_file="${CONF_FILE:-/etc/syslog-ng/syslog-ng.conf}"
 options="$OPTIONS"
+persist_file="${PERSIST_FILE:-/var/lib/syslog-ng/syslog-ng.persist}"
 
+kv[user]="${USER:-root}"
 kv[search_pattern]="$binary"
-kv[log]="/var/log/syslog-ng.log"
+kv[log]="${LOG_FILE:-/var/log/syslog-ng.log}"
 
 ###############################################################################
 
 kv.addCommand "start"        "Start ${kv[prog_name]}"
 kv.addCommand "stop"         "Stop ${kv[prog_name]}"
-kv.addCommand "restart"      "Restart (stop+start) ${kv[prog_name]}"
+kv.addCommand "restart"      "Restart (stop+start) ${kv[prog_name]}" "restart"
 kv.addCommand "status"       "Show current status of ${kv[prog_name]}"
 kv.addCommand "check"        "Validate config" "check"
 kv.addCommand "reload"       "Reload ${kv[prog_name]}" "reload"
@@ -41,6 +44,27 @@ kv.addHandler "stop"    "stopServiceHandler"
 kv.disableOutputRedirect "start" "pre"
 
 ###############################################################################
+
+prepare() {
+  local has_errors=""
+
+  [[ ! -f $binary ]] && has_errors=true && kv.error "Error! File <$binary> does not exist"
+  [[ ! -x $binary ]] && has_errors=true && kv.error "Error! File <$binary> does not executable"
+
+  [[ ! -f $conf_file ]] && has_errors=true && kv.error "Error! File <$conf_file> does not exist"
+  [[ ! -r $conf_file ]] && has_errors=true && kv.error "Error! File <$conf_file> does not readable"
+
+  [[ ! -f $persist_file ]] && has_errors=true && kv.error "Error! File <$persist_file> does not exist"
+  [[ ! -r $persist_file ]] && has_errors=true && kv.error "Error! File <$persist_file> does not readable"
+
+  [[ -z ${kv[user]} ]] && has_errors=true && kv.error "User value can't be empty"
+
+  if ! kv.hasUser "${kv[user]}" ; then
+    has_errors=true && kv.error "User <${kv[user]}> not found in /etc/passwd file"
+  fi
+
+  [[ $has_errors ]] && kv.exit $ACTION_ERROR
+}
 
 preStartServiceHandler() {
   if ! testServiceConfig true ; then
@@ -59,7 +83,7 @@ postStartServiceHandler() {
 }
 
 startServiceHandler() {
-  kv.daemonize "$binary" "-r -f $conf_file -p ${kv[pid_file]} $options"
+  kv.daemonize "$binary" "-r -f $conf_file -p ${kv[pid_file]} --user ${kv[user]} --persist-file $persist_file $options"
 
   [[ $? -ne $ACTION_OK ]] && return $ACTION_ERROR
 
@@ -157,5 +181,6 @@ reload() {
 
 ###############################################################################
 
-kv.go $@
+prepare
 
+kv.go $@
