Fixes for vault init scripts

diff --git a/specs/vault/SOURCES/vault-agent.init b/specs/vault/SOURCES/vault-agent.init
--- a/specs/vault/SOURCES/vault-agent.init
+++ b/specs/vault/SOURCES/vault-agent.init
@@ -31,7 +31,7 @@ kv.addCommandVars "stop" "force"
 kv.addHandler "start" "startServiceHandler"
 kv.addHandler "stop"  "stopServiceHandler"
 
-kv.addHandler "start" "preStartHandler"  "pre"
+kv.addHandler "start" "preStartHandler" "pre"
 
 kv.disableOutputRedirect "start" "pre"
 
@@ -40,19 +40,21 @@ kv.disableOutputRedirect "start" "pre"
 preStartHandler() {
   local has_errors=""
 
-  [[ ! -f $binary ]] && has_errors=true && kv.error "Error! File $binary is not exist"
-  [[ ! -x $binary ]] && has_errors=true && kv.error "Error! File $binary is not executable"
+  [[ ! -f "$binary" ]] && has_errors=true && kv.error "Error! File $binary doesn't exist"
+  [[ ! -x "$binary" ]] && has_errors=true && kv.error "Error! File $binary is not executable"
 
-  [[ ! -f $conf_file ]] && has_errors=true && kv.error "Error! File $conf_file is not exist"
-  [[ ! -r $conf_file ]] && has_errors=true && kv.error "Error! File $conf_file is not readable"
+  [[ ! -f "$conf_file" ]] && has_errors=true && kv.error "Error! File $conf_file doesn't exist"
+  [[ ! -r "$conf_file" ]] && has_errors=true && kv.error "Error! File $conf_file is not readable"
 
-  [[ -z ${kv[user]} ]] && has_errors=true && kv.error "User value can't be empty"
+  [[ -z "${kv[user]}" ]] && has_errors=true && kv.error "User value can't be empty"
 
   if ! kv.hasUser "${kv[user]}" ; then
     has_errors=true && kv.error "User ${kv[user]} not found in /etc/passwd file"
   fi
 
-  [[ $has_errors ]] && kv.exit $ACTION_ERROR
+  [[ -n "$has_errors" ]] && kv.exit $ACTION_ERROR
+
+  return $ACTION_OK
 }
 
 startServiceHandler() {
