Vault init script refactoring

diff --git a/specs/vault/SOURCES/vault-server.init b/specs/vault/SOURCES/vault-server.init
--- a/specs/vault/SOURCES/vault-server.init
+++ b/specs/vault/SOURCES/vault-server.init
@@ -31,24 +31,26 @@ kv.addCommandVars "stop" "force"
 kv.addHandler "start" "startServiceHandler"
 kv.addHandler "stop"  "stopServiceHandler"
 
+kv.addHandler "start" "preStartHandler"  "pre"
+
 ###############################################################################
 
-prepare() {
+preStartHandler() {
   local has_errors=""
 
-  [[ ! -f $binary ]] && has_errors=true && kv.error "Error! File <$binary> is not exist"
-  [[ ! -x $binary ]] && has_errors=true && kv.error "Error! File <$binary> is not executable"
+  [[ ! -f "$binary" ]] && has_errors=true && kv.error "Error! File $binary doesn't exist"
+  [[ ! -x "$binary" ]] && has_errors=true && kv.error "Error! File $binary is not executable"
 
-  [[ ! -f $conf_file ]] && has_errors=true && kv.error "Error! File <$conf_file> is not exist"
-  [[ ! -r $conf_file ]] && has_errors=true && kv.error "Error! File <$conf_file> is not readable"
+  [[ ! -f "$conf_file" ]] && has_errors=true && kv.error "Error! File $conf_file doesn't exist"
+  [[ ! -r "$conf_file" ]] && has_errors=true && kv.error "Error! File $conf_file is not readable"
 
-  [[ -z ${kv[user]} ]] && has_errors=true && kv.error "User value can't be empty"
+  [[ -z "${kv[user]}" ]] && has_errors=true && kv.error "User value can't be empty"
 
   if ! kv.hasUser "${kv[user]}" ; then
-    has_errors=true && kv.error "User <${kv[user]}> not found in /etc/passwd file"
+    has_errors=true && kv.error "User ${kv[user]} not found in /etc/passwd file"
   fi
 
-  [[ $has_errors ]] && kv.exit $ACTION_ERROR
+  [[ -n $has_errors ]] && kv.exit $ACTION_ERROR
 }
 
 startServiceHandler() {
@@ -84,7 +86,5 @@ stopServiceHandler() {
 }
 
 ###############################################################################
-
-prepare
 
 kv.go $@
